server:
  port: 10001
spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      routes:
        - id: user-gateway
          uri: http://localhost:8060
          order: 1
          predicates:
            - Path=/server-user/**
            #自定义断言
            #- Name=plus
          filters:
            - StripPrefix=1
            #局部过滤器
            #- AddRequestHeader=IP,localhost
            #- AddRequestParameter=name,plus
            #- SetStatus=1001
            #自定义局部过滤器
            - Grayscale=true

#      routes:
#        - id: user-gateway
#          uri: http://localhost:8060
#          order: 1
#          predicates:
#            - Path=/server-user/**
#            - RemoteAddr=192.168.130.254/24
#            - Method=GET
#          filters:
#            - StripPrefix=1

